In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.2.1'

In [3]:
import numpy as np

In [4]:
test_data = np.array(list(range(100)))
# np.random.shuffle(test_data)
test_data = test_data.reshape(10, 10)
test_data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
test_data = test_data.reshape(1, 10, 10, 1)

In [6]:
tensor = tf.placeholder(tf.float32, shape=[1, 10, 10, 1])

In [7]:
tensor

<tf.Tensor 'Placeholder:0' shape=(1, 10, 10, 1) dtype=float32>

In [8]:
Fractional = tf.nn.fractional_max_pool(tensor,
                                       [1.0, 1.4, 1.4, 1],
                                       True,
                                       True)
Fractional

FractionalMaxPool(output=<tf.Tensor 'FractionalMaxPool:0' shape=(1, 7, 7, 1) dtype=float32>, row_pooling_sequence=<tf.Tensor 'FractionalMaxPool:1' shape=(7,) dtype=int64>, col_pooling_sequence=<tf.Tensor 'FractionalMaxPool:2' shape=(7,) dtype=int64>)

In [9]:
with tf.Session() as sess:
    p2, r2, c2 = sess.run(Fractional, feed_dict = {tensor : test_data})

In [10]:
p2_np = np.array(p2)
p2_np = p2_np.reshape(7, 7)
p2_np

array([[ 12.,  13.,  15.,  16.,  18.,  19.,  19.],
       [ 32.,  33.,  35.,  36.,  38.,  39.,  39.],
       [ 42.,  43.,  45.,  46.,  48.,  49.,  49.],
       [ 62.,  63.,  65.,  66.,  68.,  69.,  69.],
       [ 72.,  73.,  75.,  76.,  78.,  79.,  79.],
       [ 82.,  83.,  85.,  86.,  88.,  89.,  89.],
       [ 92.,  93.,  95.,  96.,  98.,  99.,  99.]], dtype=float32)

In [11]:
print(r2)
print(c2)

[ 0  1  3  4  6  7  8 10]
[ 0  2  3  5  6  8  9 10]
